### PR TITLE
Branch tab daily

### LINKED ISSUE #136: [PE-D] List command only lists pending tasks
It appears this was an intended implementation, however the UG states "all tasks". Only those pending were listed in the display window. This also suggests that tasks in the other 2 columns cannot be indexed?

Expected outcome: List all tasks
Actual outcome: Only lists pending tasks
Screenshot:

Steps to reproduce:
1. Enter "list" and submit.
2. Check that the display window only lists pending tasks.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lamlaaaam/ped#2

### LINKED ISSUE #140: [PE-D] Unfinished todo implementation
Not sure if it's intended but this tab only has the feature of adding. There is no way to mark the tasks here as done or remove them. Since the tracker is meant to keep track of tasks, it appears to be a feature flaw if users cannot resolve the daily tasks.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: lamlaaaam/ped#6

### LINKED ISSUE #159: [PE-D] Daily tab does not display daily tasks automatically
When a task whose deadline is on the day added (or once we reach a day where the task's deadline falls on that day), it would make sense to automatically shift this task to the daily todo tracker instead of having to manually assign it there.

Perhaps there could be a listener to watch out for this?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: erisjacey/ped#5

### LINKED ISSUE #167: [PE-D] Editing task name is not reflected elsewhere
Reproduce:
1. Add task
2. add task to todo
3. rename the task

Results:
Taskname in pending task no longer same as task in todo

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: li-s/ped#5

### LINKED ISSUE #168: [PE-D] Done tasks still appear in daily tasks
Reproduce steps:
1. Add a task
2. Add it to todo
3. Mark task as done

Result:
Task is done but still show up in todo

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: li-s/ped#6

### LINKED ISSUE #169: [PE-D] Expired tasks still in todo list
Reproduce:
1. Create a task
2. Add it to the daily
3. Wait until it expires

Result:
The task is expired, but is still under the daily todo tab.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: li-s/ped#7

### PR DESCRIPTION
**Pull request by yingqi0607**

### CODE REVIEW

File: src/main/java/seedu/tr4cker/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -118,6 +129,19 @@ protected static Task createEditedTask(Task taskToEdit, EditTaskDescriptor editT
                 updatedTaskDescription, updatedModuleCode, initialTags);
     }
 
+    /**
+     * Creates and returns a {@code Todo} with the details of {@code todoToEdit}
+     * edited with {@code editTodoDescriptor}.
+     */
+    protected static Todo createEditedTodo(Todo todoToEdit, EditTodoDescriptor editTodoDescriptor) {
+        assert todoToEdit != null;
```
Comment (ruilingk) [inline src/main/java/seedu/tr4cker/logic/commands/EditCommand.java]: im not sure if using `requireNonNull(todoToEdit)` would be better?

File: src/main/java/seedu/tr4cker/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -248,4 +272,66 @@ public boolean equals(Object other) {
...
+        }
+
+        /**
+         * Returns true if at least one field is edited.
+         */
+        public boolean isAnyFieldEdited() {
+            return CollectionUtil.isAnyNonNull(name, deadline);
+        }
+
+        public void setName(Name name) {
```
Comment (ruilingk) [inline src/main/java/seedu/tr4cker/logic/commands/EditCommand.java:304]: missing javadocs for public methods

File: src/main/java/seedu/tr4cker/logic/commands/DailyCommand.java [hunk 3]
```diff
@@ -11,15 +20,45 @@
 
     public static final String MESSAGE_SWITCH_TAB_SUCCESS = "Switched to Daily tab!";
 
+    public static final String MESSAGE_USAGE = "Looks like you're trying to use the " + COMMAND_WORD + " command: "
```
Comment (ruilingk) [inline src/main/java/seedu/tr4cker/logic/commands/DailyCommand.java:23]: is this the message usage for all daily commands?

**Review by ruilingk — COMMENTED** [review]
minor tweaks and it lgtm

File: src/main/java/seedu/tr4cker/logic/commands/DailyCommand.java [hunk 4]
```diff
@@ -11,15 +20,45 @@
...
      * Constructor for DailyCommand when user wants to switch to Daily tab.
      */
     public DailyCommand() {
+        this.toDeleteIndex = null;
+    }
+
+    /**
+     * Constructor for DailyCommand when user wants to delete a todo task.
+     */
+    public DailyCommand(Index toDeleteIndex) {
```
Comment (ruilingk) [inline src/main/java/seedu/tr4cker/logic/commands/DailyCommand.java:44]: is there another constructor for editing?

**Review by ruilingk — APPROVED** [review]
lgtm!
