### PR TITLE
Branch feature done command: Add Test cases and Bug fix

### LINKED ISSUE #166: [PE-D] Done gives different message when index is out of bound
Reproduction:
1. done 0 p/100. output:  long  help message
2. done 1000 p/100. output: The task index provided is invalid

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: li-s/ped#2

### PR DESCRIPTION
**Pull request by hanweic53**

### CODE REVIEW

File: src/main/java/seedu/tr4cker/commons/util/StringUtil.java [hunk 1]
```diff
@@ -68,4 +68,22 @@ public static boolean isNonZeroUnsignedInteger(String s) {
             return false;
         }
     }
+
+    /**
+     * Returns true if {@code s} represents an integer
+     * e.g. -1, 0, 1, 2, ..., {@code Integer.MAX_VALUE} <br>
```
Comment (ruilingk) [inline src/main/java/seedu/tr4cker/commons/util/StringUtil.java:74]: think u forgot to remove `<br>`

File: src/test/java/seedu/tr4cker/model/ModelManagerTest.java [hunk 2]
```diff
@@ -113,6 +130,22 @@ public void getFilteredTaskList_modifyList_throwsUnsupportedOperationException()
...
+    public void getFilteredExpiredTaskList_modifyList_throwsUnsupportedOperationException() {
+        assertThrows(UnsupportedOperationException.class, () -> modelManager.getFilteredExpiredTaskList().remove(0));
+    }
+
+    @Test
+    public void getFilteredCompletedTaskList_modifyList_throwsUnsupportedOperationException() {
+        assertThrows(UnsupportedOperationException.class, () -> modelManager.getFilteredCompletedTaskList().remove(0));
+    }
+
+
```
Comment (ruilingk) [inline src/test/java/seedu/tr4cker/model/ModelManagerTest.java]: extra line

**Review by ruilingk — COMMENTED** [review]
some minor changes and it lgtm

**Review by ruilingk — APPROVED** [review]
lgtm
