### PR TITLE
Edit Sample Data for Task Name and Fix UI bug

### LINKED ISSUE #22: Refactor Name class to TaskName class

### PR DESCRIPTION
**Pull request by hanweic53**

### CODE REVIEW

File: src/test/java/seedu/tr4cker/logic/commands/AddCommandTest.java [hunk 1]
```diff
@@ -53,26 +53,26 @@ public void execute_duplicateTask_throwsCommandException() {
 
     @Test
     public void equals() {
-        Task alice = new TaskBuilder().withName("Alice").build();
-        Task bob = new TaskBuilder().withName("Bob").build();
-        AddCommand addAliceCommand = new AddCommand(alice);
-        AddCommand addBobCommand = new AddCommand(bob);
+        Task task1 = new TaskBuilder().withName("homework").build();
+        Task task2 = new TaskBuilder().withName("assignment").build();
```
Comment (cwenling) [inline src/test/java/seedu/tr4cker/logic/commands/AddCommandTest.java]: might be more intuitive if the variable name is the same as the task name?

**Review by cwenling — CHANGES_REQUESTED** [review]
minor change

**Review by cwenling — APPROVED** [review]
LGTM
